[package]
name = "iaus"
version = "0.1.0"
authors = ["jaynus <jaynus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
rayon = "1"
priority-queue = "0.6"
derivative = "1"

[dev-dependencies]
env_logger = "0.6"
plotters = "0.2"